SET(CPPUNIT_FOUND "NO")

FIND_PATH(CPPUNIT_CPPUNIT_INCLUDE_DIR TestCase.h
  /usr/local/include
  /usr/include/
  /usr/include/cppunit
  )

SET(CPPUNIT_NAMES ${CPPUNIT_NAMES} cppunit libcppunit)
FIND_LIBRARY(CPPUNIT_LIBRARY
  NAMES ${CPPUNIT_NAMES}
  PATHS /usr/lib /usr/local/lib
)

IF (CPPUNIT_LIBRARY)
    SET(CPPUNIT_INCLUDE_DIR ${CPPUNIT_CPPUNIT_INCLUDE_DIR})
    SET(CPPUNIT_LIBRARIES ${CPPUNIT_LIBRARY})
    SET(CPPUNIT_FOUND "YES")
ENDIF (CPPUNIT_LIBRARY)

IF (CPPUNIT_FOUND)
  MESSAGE(STATUS "Found CppUnit: ${CPPUNIT_LIBRARY}")
ELSE (CPPUNIT_FOUND)
  MESSAGE(FATAL_ERROR "Could not find CppUnit library")
ENDIF (CPPUNIT_FOUND)

MARK_AS_ADVANCED(CPPUNIT_CPPUNIT_INCLUDE_DIR CPPUNIT_LIBRARY)