# Find libevent includes and library

# This moduel defines
#   EVENT_INCLUDE_DIR
#   EVENT_LIBRARIES
#   EVENT_FOUND

SET(EVENT_FOUND "NO")

FIND_PATH(EVENT_EVENT_INCLUDE_DIR event.h
  /usr/include
  /usr/local/include
)

SET(EVENT_NAMES ${EVENT_NAMES} event libevent)
FIND_LIBRARY(EVENT_LIBRARY
  NAMES ${EVENT_NAMES}
  PATHS /usr/lib /usr/local/lib
)

IF(EVENT_LIBRARY)
  SET(EVENT_INCLUDE_DIR ${EVENT_EVENT_INCLUDE_DIR})
  SET(EVENT_LIBRARIES ${EVENT_LIBRARY})
  SET(EVENT_FOUND "YES")
ENDIF(EVENT_LIBRARY)

IF(EVENT_FOUND)
  MESSAGE(STATUS "Found libevent: ${EVENT_LIBRARIES}")
ELSE(EVENT_FOUND)
  MESSAGE(FATAL_ERROR "Could not find libevent")
ENDIF(EVENT_FOUND)

MARK_AS_ADVANCED(EVENT_EVENT_INCLUDE_DIR EVENT_LIBRARY)