/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "kumonosu_server_constants.h"

namespace kumonosu {

const kumonosu_serverConstants g_kumonosu_server_constants;

kumonosu_serverConstants::kumonosu_serverConstants() {
}

} // namespace

