/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef kumonosu_server_CONSTANTS_H
#define kumonosu_server_CONSTANTS_H

#include "kumonosu_server_types.h"

namespace kumonosu {

class kumonosu_serverConstants {
 public:
  kumonosu_serverConstants();

};

extern const kumonosu_serverConstants g_kumonosu_server_constants;

} // namespace

#endif
