# Find Apache Thrift includes and library

# This module defines
#   THRIFT_INCLUDE_DIR
#   THRIFT_LIBRARIES
#   THRIFT_FOUND

SET(THRIFT_FOUND "NO")

FIND_PATH(THRIFT_THRIFT_INCLUDE_DIR Thrift.h
  /usr/local/include
  /usr/include
  /usr/local/include/thrift
  )

SET(THRIFT_NAMES ${THRIFT_NAMES} thrift libthrift)
FIND_LIBRARY(THRIFT_LIBRARY
  NAMES ${THRIFT_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

SET(THRIFTNB_NAMES ${THRIFTNB_NAMES} thriftnb libthriftnb)
FIND_LIBRARY(THRIFTNB_LIBRARY
  NAMES ${THRIFTNB_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (THRIFT_LIBRARY AND THRIFTNB_LIBRARY)
    SET(THRIFT_INCLUDE_DIR ${THRIFT_THRIFT_INCLUDE_DIR})
    SET(THRIFT_LIBRARIES ${THRIFT_LIBRARY} ${THRIFTNB_LIBRARY})
    SET(THRIFT_FOUND "YES")
ENDIF (THRIFT_LIBRARY AND THRIFTNB_LIBRARY)

IF (THRIFT_FOUND) 
  MESSAGE(STATUS "Found Thrift: ${THRIFT_LIBRARIES}")
ELSE (THRIFT_FOUND)
  MESSAGE(FATAL_ERROR "Could not find Thrift library")
ENDIF (THRIFT_FOUND)

MARK_AS_ADVANCED(THRIFT_THRIFT_INCLUDE_DIR THRIFT_LIBRARY)